---
- name: "configuration play."
  hosts: web
  user: ec2-user
  become: true
  become_method: sudo
  become_user: ec2-user
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
    - buildnumber: "23" 


  pre_tasks:
    - name: "wait 600 seconds for target connection to become reachable/usable."
      wait_for:
        timeout: 3

  tasks:
    - name: print message
      ansible.builtin.debug:
        msg: "Build Number is {{ buildnumber }}"
        

  roles:
    # - setup
    - deploy
    #- configure-prometheus-node-exporter
