 vars:
    repository: https://github.com/nicgirault/cinelocal-api.git
    path: /home/ubuntu/www
    image: nicgirault/cinelocal-api
- name: "rolling update to K8"
  shell: |
    ls -l
    kubectl set image deployment/python-housek8s-prod houseimg=colmoconchuir/capapp:0.1.23 -n=production
    echo {{ path }}
    echo {{ myTestVAR }}