- name: "rolling update to K8"
  shell: |
    ls -l
    kubectl set image deployment/python-housek8s-prod houseimg=colmoconchuir/capapp:0.1.23 -n=production

- name: print message
  ansible.builtin.debug:
    msg: "WORKFLOW ID is {{ fruit }}"
    
        