- name: "deploy new app"
  shell: |
    ls -l
    kubectl create namespace production-{{ buildnumber }}
    dockerpath=colmoconchuir/capapp:0.1.{{ buildnumber }}
    kubectl create deployment python-housek8s-production-{{ buildnumber }} --image=$dockerpath -n=production-{{ buildnumber }}
    kubectl expose deployment python-housek8s-production-{{ buildnumber }} --type=LoadBalancer --port=8000 --target-port=80 -n=production-{{ buildnumber }}
    touch /tmp/test7
    kubectl get svc -n=production-{{ buildnumber }} > /tmp/test7
    sleep 20
    
- name: "get ELB URL"
  shell: |
    touch /tmp/URL
    echo kubectl get svc -n=production-{{ buildnumber }} | awk '{print $4}' | awk '(NR>1)'
    kubectl get svc -n=production-{{ buildnumber }}| awk '{print $4}' | awk '(NR>1)' > /tmp/URL

- name: print message
  ansible.builtin.debug:
    msg: "WORKFLOW ID is {{ buildnumber }}"
    
- name: LoadBalancer
  shell: |
    echo "ELB is: "
    cat /tmp/URL