# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1


jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      # run lint!!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint
      - run:
          name: build docker
          command: |
          # . venv/bin/activate
          # docker build --tag=house .
          # docker image ls
          # docker run -p 8000:80 house

            
  configure-infrastructure:
    docker:
      - image: cimg/go:1.17
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
          
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo “$DOCKERHUB_PASSWORD” | docker login -u “$DOCKERHUB_USERNAME” — password-stdin
            docker build -t myTestIMG .
            docker push colmoconchuir/myTestIMG
             
workflows:
  default:
    jobs:
     # - deploy-infrastructure
     # - build:
    #      requires: [deploy-infrastructure]
      - configure-infrastructure
          #requires: [build]
            