---
- name: "testing"
  shell: |
    ls -l
    pwd
    cd /home/ec2-user/
    mkdir testdir
    cd testdir
    touch testfile.txt
    whoami > testfile.txt

- name: "deploy EKS"
  shell: |
    ls -l
    eksctl create cluster --name production-{{ buildnumber }} --region=us-west-2 --nodes=2 --node-type t3.medium  
    
    

#- name: "get results"
#  shell: |
#    cd /home/ec2-user/environment/k8smicroservicesapp_aws
#    ./make_prediction.sh >> /home/ec2-user/testdir/testfile.txt